server:
  port: 8089

logging:
  level:
    org.springframework.security: trace

spring:
  application:
    name: fsp_platform
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${auth0audience-issuer-uri}
          audiences: ${auth0audience-audience}
